// @generated
// This file is @generated by prost-build.
// ///// Core Messages ///////

/// A survey containing questions and metadata for conducting user surveys
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Survey {
    /// The project identifier for this survey. Equal to the parent of the corresponding Agent.
    /// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
    /// Read-only in the Survey message (assigned by the back-end)
    #[prost(string, tag="1")]
    pub survey_id: ::prost::alloc::string::String,
    /// Required. The (human readable) name of this survey
    #[prost(string, tag="2")]
    pub display_name: ::prost::alloc::string::String,
    /// Required. The language of the agent created for the survey.
    /// This is also the only supported language of the agent.
    /// ISO 639-1 language code
    #[prost(string, tag="3")]
    pub language_code: ::prost::alloc::string::String,
    /// Required. List of questions to be asked during the survey.
    #[prost(message, repeated, tag="7")]
    pub questions: ::prost::alloc::vec::Vec<Question>,
    /// Required. Information about the entity behind the survey, the purpose of the survey, legal stuff, etc.
    #[prost(message, optional, tag="8")]
    pub survey_info: ::core::option::Option<SurveyInfo>,
    /// Optional. List of subflows excluded for this survey.
    #[prost(enumeration="SubFlow", repeated, tag="9")]
    pub exclude_subflows: ::prost::alloc::vec::Vec<i32>,
    /// Current status of the NLU Agent respecting to the Survey
    #[prost(enumeration="survey::AgentStatus", tag="10")]
    pub status: i32,
}
/// Nested message and enum types in `Survey`.
pub mod survey {
    // Note: All other attributes of the Agent message should be updated using the std mechanism of UpdateAgent once the survey has been created.

    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum AgentStatus {
        /// Agent has not been initialized yet
        ToBeInitialized = 0,
        /// Agent has been successfully updated and is current
        Updated = 1,
        /// Agent is currently being updated
        Updating = 2,
        /// Agent is outdated and needs to be updated
        Outdated = 3,
    }
    impl AgentStatus {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::ToBeInitialized => "TO_BE_INITIALIZED",
                Self::Updated => "UPDATED",
                Self::Updating => "UPDATING",
                Self::Outdated => "OUTDATED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TO_BE_INITIALIZED" => Some(Self::ToBeInitialized),
                "UPDATED" => Some(Self::Updated),
                "UPDATING" => Some(Self::Updating),
                "OUTDATED" => Some(Self::Outdated),
                _ => None,
            }
        }
    }
}
/// <p>Collect information about the entity behind the survey, the purpose of the survey, legal stuff, etc.</p>
/// <p>This is needed to generate meaningful messages and training data for some of the auto-generated intents.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SurveyInfo {
    /// Required unless SubFlow.LEGAL_ENTITY is deselected.
    /// The legal entity (company, research institute, etc.) on whose behalf the survey is performed
    #[prost(string, tag="1")]
    pub legal_entity: ::prost::alloc::string::String,
    /// Required unless SubFlow.POSTAL_ADDRESS is deselected.
    /// The postal address to which callees can direct any requests.
    #[prost(string, tag="2")]
    pub postal_address: ::prost::alloc::string::String,
    /// Required unless SubFlow.EMAIL_ADDRESS is deselected.
    /// The email address to which callees can direct any requests.
    #[prost(string, tag="3")]
    pub email_address: ::prost::alloc::string::String,
    /// Required unless SubFlow.PHONE_NUMBER is deselected.
    /// The phone number to which callees can direct any requests.
    #[prost(string, tag="4")]
    pub phone_number: ::prost::alloc::string::String,
    /// Required unless SubFlow.PHONE_HOURS is deselected.
    /// The phone hours during which callees can call (in pronounceable form).
    #[prost(string, tag="5")]
    pub phone_hours: ::prost::alloc::string::String,
    /// Required unless SubFlow.EXPECTED_DURATION is deselected.
    /// The expected duration of the survey (in pronounceable form)
    #[prost(string, tag="6")]
    pub expected_duration: ::prost::alloc::string::String,
    /// Required unless SubFlow.PURPOSE is deselected.
    /// An explanation regarding the purpose of the survey (in pronounceable form)
    #[prost(string, tag="7")]
    pub purpose: ::prost::alloc::string::String,
    /// Required.
    /// A one-word explanation of the survey topic (in pronounceable form)
    #[prost(string, tag="8")]
    pub topic: ::prost::alloc::string::String,
    /// Required.
    /// A pronounceable explanation of the legal implications of participating in the survey.
    /// For example: &quot;Your answers during this survey will be stored anonymously for the next two years and then deleted.&quot;
    /// Should be formulated such that the agent can afterwards ask for the consent of the user.
    /// Example for how the agent could continue: &quot;Are you willing to participate in this survey?&quot;
    #[prost(string, tag="9")]
    pub legal_disclaimer: ::prost::alloc::string::String,
    /// Optional.
    /// Defaults to False. Allows the definition of a survey as anonymous or not.
    /// If the survey is not anonymous, the name of the people as well as their number will be recorded
    #[prost(bool, tag="10")]
    pub anonymous: bool,
}
/// A question that can be one of several question types: open-ended, single choice, multiple choice, scale, or parameter-based questions
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Question {
    #[prost(oneof="question::Question", tags="1, 2, 3, 4, 5, 6")]
    pub question: ::core::option::Option<question::Question>,
}
/// Nested message and enum types in `Question`.
pub mod question {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Question {
        /// A question to which any kind of reply can be given and recorded
        #[prost(message, tag="1")]
        OpenQuestion(super::OpenQuestion),
        /// A question for which exactly one out of a predefined set of options is expected as answer
        #[prost(message, tag="2")]
        SingleChoiceQuestion(super::SingleChoiceQuestion),
        /// A question for which exactly one or more out of a predefined set of options are expected as answers
        #[prost(message, tag="3")]
        MultipleChoiceQuestion(super::MultipleChoiceQuestion),
        /// convenience wrapper around a SingleChoiceQuestion
        #[prost(message, tag="4")]
        ScaleQuestion(super::ScaleQuestion),
        /// A question for which one or more entities of a particular type are expected as answers
        #[prost(message, tag="5")]
        SingleParameterQuestion(super::SingleParameterQuestion),
        /// A question for which one or more entities of a particular type are expected as answers
        #[prost(message, tag="6")]
        MultipleParameterQuestion(super::MultipleParameterQuestion),
    }
}
/// <p>A question to which any kind of reply can be given and recorded</p>
/// <p>fixme: not working yet</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenQuestion {
    /// The text which introduces the question (should be pronounceable)
    #[prost(string, tag="1")]
    pub question_text: ::prost::alloc::string::String,
}
/// <p>A question for which exactly one out of a predefined set of options is expected as answer</p>
/// <p>Example: <code>SingleChoiceQuestion(question_text=&apos;Who is your favorite movie hero?&apos;, choices=\[Choice(synonyms=[&apos;Bond&apos;, &apos;James Bond&apos;\]), Choice(synonyms=\[&apos;Batman&apos;\]), Choice(synonyms=\[&apos;Superman&apos;, &apos;Clark Kent&apos;\])])</code></p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingleChoiceQuestion {
    /// The text which introduces the question (should be pronounceable)
    #[prost(string, tag="1")]
    pub question_text: ::prost::alloc::string::String,
    /// List of choices which are accepted for this question
    /// Each Choice is represented by lists of synonyms.
    /// Note: needs to contain at least 2 choices
    #[prost(message, repeated, tag="2")]
    pub choices: ::prost::alloc::vec::Vec<Choice>,
}
/// <p>A question for which exactly one or more out of a predefined set of options are expected as answers</p>
/// <p>Example: <code>MultipleChoiceQuestion(question_text=&apos;Which colors do you like?&apos;, choices=\[Choice(synonyms=[&apos;red&apos;, &apos;reddisch&apos;\]), Choice(synonyms=\[&apos;blue&apos;, &apos;blueish&apos;\]), Choice(synonyms=\[&apos;yellow&apos;\])])</code></p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MultipleChoiceQuestion {
    /// The text which introduces the question (should be pronounceable)
    #[prost(string, tag="1")]
    pub question_text: ::prost::alloc::string::String,
    /// List of choices which are accepted for this question
    /// Each Choice is represented by lists of synonyms.
    /// Note: needs to contain at least 2 choices
    #[prost(message, repeated, tag="2")]
    pub choices: ::prost::alloc::vec::Vec<Choice>,
}
/// A question for which an answer on a user-defined scale is expected
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScaleQuestion {
    /// The text which introduces the question (should be pronounceable)
    #[prost(string, tag="1")]
    pub question_text: ::prost::alloc::string::String,
    /// Minimum value and label for the scale
    #[prost(message, optional, tag="2")]
    pub min_value: ::core::option::Option<scale_question::ScaleValue>,
    /// Maximum value and label for the scale
    #[prost(message, optional, tag="3")]
    pub max_value: ::core::option::Option<scale_question::ScaleValue>,
}
/// Nested message and enum types in `ScaleQuestion`.
pub mod scale_question {
    /// Represents a value and label pair for scale question endpoints
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ScaleValue {
        /// Numeric value for this scale point
        #[prost(int32, tag="1")]
        pub value: i32,
        /// Human-readable label for this scale point
        #[prost(string, tag="2")]
        pub label: ::prost::alloc::string::String,
    }
}
/// <p>SingleParameterQuestion defines a question which prompts the user for one entity of a particular type</p>
/// <p>Example: <code>SingleParameterQuestion(question_text=&apos;How old are you?&apos;, parameter_type=&apos;sys.number&apos;)</code></p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SingleParameterQuestion {
    /// The text which introduces the question (should be pronounceable)
    #[prost(string, tag="1")]
    pub question_text: ::prost::alloc::string::String,
    /// The display name of the entity (type) which is accepted as an answer to this question
    /// Note: the corresponding entity_type must exist (system entity type) and is not automatically created
    #[prost(string, tag="2")]
    pub parameter_type: ::prost::alloc::string::String,
}
/// <p>MultipleParameterQuestion defines a question which prompts the user for one or several entities of one particular type</p>
/// <p>Example: <code>MultipleParameterQuestion(question_text=&apos;How old are your children?&apos;, parameter_type=&apos;sys.number&apos;)</code></p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MultipleParameterQuestion {
    /// The text which introduces the question (should be pronounceable)
    #[prost(string, tag="1")]
    pub question_text: ::prost::alloc::string::String,
    /// The display name of the entity (type) which is accepted as an answer to this question
    /// Note: the corresponding entity_type must exist (system entity type) and is not automatically created
    #[prost(string, tag="2")]
    pub parameter_type: ::prost::alloc::string::String,
}
/// <p>The Choice message defines one &quot;option&quot; for the SingleChoiceQuestion and MultipleChoiceQuestion question types</p>
/// <p>Example: <code>Choice(synonyms=\[&quot;blue&quot;, &quot;blueish&quot;, &quot;pale blue&quot;, &quot;deep blue&quot;\])</code></p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Choice {
    /// The synonyms which are recognized as equivalent for identifying one option
    #[prost(string, repeated, tag="1")]
    pub synonyms: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional; Nested question if this specific choice gets chosen.
    /// Note: the follow-up question is only available for the SingleChoiceQuestion
    #[prost(message, optional, tag="2")]
    pub follow_up_question: ::core::option::Option<Question>,
    /// The &quot;canonical value&quot; (i.e. the entity value)
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
}
/// An answer to a survey question collected during a session
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Answer {
    /// the number of the question to which this answer belongs
    #[prost(int64, tag="1")]
    pub question_nr: i64,
    /// the ID of the session on which the answer was collected
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
    /// Required; the full answer text
    #[prost(string, tag="3")]
    pub answer_text: ::prost::alloc::string::String,
    /// fixme: better names and doc-strings below
    /// Optional; contains the normalized value of the selected option (parameter) extracted
    #[prost(string, tag="4")]
    pub answer_parameter: ::prost::alloc::string::String,
    /// Optional; contains the original text of the selected option (parameter) extracted
    #[prost(string, tag="5")]
    pub answer_parameter_original: ::prost::alloc::string::String,
    #[prost(oneof="answer::IsAnonymous", tags="7, 6")]
    pub is_anonymous: ::core::option::Option<answer::IsAnonymous>,
}
/// Nested message and enum types in `Answer`.
pub mod answer {
    /// User information for non-anonymous surveys
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct UserInfo {
        /// First name of the User to be surveyed
        #[prost(string, tag="1")]
        pub first_name: ::prost::alloc::string::String,
        /// Last name of the User to be surveyed
        #[prost(string, tag="2")]
        pub last_name: ::prost::alloc::string::String,
        /// Phone number of the User to be surveyed
        #[prost(string, tag="3")]
        pub phone_number: ::prost::alloc::string::String,
        /// the ID of the session on which the answer was collected
        #[prost(string, tag="4")]
        pub session_id: ::prost::alloc::string::String,
        /// Unique identifier of the User to be surveyed
        #[prost(string, tag="5")]
        pub user_id: ::prost::alloc::string::String,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum IsAnonymous {
        /// True if the survey is anonymous, false otherwise
        #[prost(bool, tag="7")]
        Anonymous(bool),
        /// User information if the survey is not anonymous
        #[prost(message, tag="6")]
        UserInformation(UserInfo),
    }
}
// ///// Request / Response messages ///////

/// Request message for creating a new survey
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSurveyRequest {
    /// The survey to create
    #[prost(message, optional, tag="1")]
    pub survey: ::core::option::Option<Survey>,
}
/// Request message for retrieving a survey
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSurveyRequest {
    /// The project identifier for this survey. Equal to the parent of the corresponding Agent.
    /// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
    #[prost(string, tag="1")]
    pub survey_id: ::prost::alloc::string::String,
}
/// Request message for updating an existing survey
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateSurveyRequest {
    /// Updated survey. Note: the ID must refer to an existing survey which will be updated
    #[prost(message, optional, tag="1")]
    pub survey: ::core::option::Option<Survey>,
    /// Optional. Field mask that defines which fields get updated. Default: all fields are updated.
    /// Example: <code>update_mask = FieldMask(\[&apos;survey.display_name&apos;, &apos;survey.questions&apos;\])</code>
    #[prost(message, optional, tag="2")]
    pub update_mask: ::core::option::Option<::prost_types::FieldMask>,
}
/// Request message for deleting a survey
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSurveyRequest {
    /// The project identifier for this survey. Equal to the parent of the corresponding Agent.
    /// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
    #[prost(string, tag="1")]
    pub survey_id: ::prost::alloc::string::String,
}
/// Request message for retrieving survey answers for a specific session or user
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSurveyAnswersRequest {
    /// The project identifier for this survey. Equal to the parent of the corresponding Agent.
    /// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
    #[prost(string, tag="1")]
    pub survey_id: ::prost::alloc::string::String,
    #[prost(oneof="get_survey_answers_request::Identifier", tags="2, 3, 4")]
    pub identifier: ::core::option::Option<get_survey_answers_request::Identifier>,
}
/// Nested message and enum types in `GetSurveyAnswersRequest`.
pub mod get_survey_answers_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Identifier {
        /// ID of one specific session on which survey answers were collected (contains survey_id)
        #[prost(string, tag="2")]
        SessionId(::prost::alloc::string::String),
        /// User Identifier. Note, if the survey is anonymous there will no identifier to filter on
        #[prost(string, tag="3")]
        UserId(::prost::alloc::string::String),
        /// User phone number. Note, if the survey is anonymous there will no identifier to filter on
        #[prost(string, tag="4")]
        UserPhoneNumber(::prost::alloc::string::String),
    }
}
/// Request message for retrieving all survey answers
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAllSurveyAnswersRequest {
    /// The project identifier for this survey. Equal to the parent of the corresponding Agent.
    /// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
    #[prost(string, tag="1")]
    pub survey_id: ::prost::alloc::string::String,
}
/// Response message containing survey answers
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SurveyAnswersResponse {
    /// The project identifier for this survey. Equal to the parent of the corresponding Agent.
    /// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
    #[prost(string, tag="1")]
    pub survey_id: ::prost::alloc::string::String,
    /// all requested answers
    #[prost(message, repeated, tag="2")]
    pub answers: ::prost::alloc::vec::Vec<Answer>,
}
/// Request message for listing surveys with pagination support
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListSurveysRequest {
    /// Optional. The next_page_token value returned from a previous list request.
    /// Example:
    /// <ul>
    ///    <li>&quot;current_index-10--page_size-20&quot; - Start page -&gt; 10, Page size -&gt; 20</li>
    /// </ul>
    #[prost(string, tag="1")]
    pub page_token: ::prost::alloc::string::String,
}
/// <p>The response message for <a href="index.html#google.cloud.dialogflow.v2.Intents.ListIntents">Intents.ListIntents</a>.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSurveysResponse {
    /// The list of surveys. There will be a maximum number of items returned based on the page_token field in the request.
    #[prost(message, repeated, tag="1")]
    pub surveys: ::prost::alloc::vec::Vec<Survey>,
    /// Token to retrieve the next page of results, or empty if there are no more results in the list.
    #[prost(string, tag="2")]
    pub next_page_token: ::prost::alloc::string::String,
}
/// Request message for agent-related survey operations
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentSurveyRequest {
    /// The project identifier for this survey. Equal to the parent of the corresponding Agent.
    /// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
    #[prost(string, tag="1")]
    pub survey_id: ::prost::alloc::string::String,
}
/// Response message for agent-related survey operations
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentSurveyResponse {
    /// The parent of an agent. Equal to the survey ID.
    /// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
    #[prost(string, tag="1")]
    pub parent: ::prost::alloc::string::String,
}
/// <p>Enumeration of (some of) the subflows which are created by default</p>
/// <p>This can be used to &quot;switch off&quot; particular subflows when creating an agent during CreateSurvey</p>
/// <p>Subflows are defined as one of the following:</p>
/// <ul>
///    <li>sequences of intents A -&gt; B_1, ..., B_n -&gt; ... -&gt; Z_1, ..., Z_m which are linked by context relationships such that the first intent in the sequence can always be triggered</li>
///    <li>single intents which can always be triggered</li>
/// </ul>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SubFlow {
    /// Not specified. This value should be never used.
    SubflowUnspecified = 0,
    /// The subflow allowing the user to inquire whether s/he is talking to a bot
    Bot = 1,
    /// The subflow allowing the user to inquire about the legal entity
    LegalEntity = 2,
    /// The subflow allowing the user to inquire about the postal address
    PostalAddress = 3,
    /// The subflow allowing the user to inquire about the email address
    EmailAddress = 4,
    /// The subflow allowing the user to inquire about the phone number
    PhoneNumber = 5,
    /// The subflow allowing the user to inquire about the phone hours
    PhoneHours = 6,
    /// The subflow allowing the user to inquire about the expected duration of the survey
    ExpectedDuration = 7,
    /// The subflow allowing the user to inquire about the purpose of the survey
    Purpose = 8,
}
impl SubFlow {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SubflowUnspecified => "SUBFLOW_UNSPECIFIED",
            Self::Bot => "BOT",
            Self::LegalEntity => "LEGAL_ENTITY",
            Self::PostalAddress => "POSTAL_ADDRESS",
            Self::EmailAddress => "EMAIL_ADDRESS",
            Self::PhoneNumber => "PHONE_NUMBER",
            Self::PhoneHours => "PHONE_HOURS",
            Self::ExpectedDuration => "EXPECTED_DURATION",
            Self::Purpose => "PURPOSE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SUBFLOW_UNSPECIFIED" => Some(Self::SubflowUnspecified),
            "BOT" => Some(Self::Bot),
            "LEGAL_ENTITY" => Some(Self::LegalEntity),
            "POSTAL_ADDRESS" => Some(Self::PostalAddress),
            "EMAIL_ADDRESS" => Some(Self::EmailAddress),
            "PHONE_NUMBER" => Some(Self::PhoneNumber),
            "PHONE_HOURS" => Some(Self::PhoneHours),
            "EXPECTED_DURATION" => Some(Self::ExpectedDuration),
            "PURPOSE" => Some(Self::Purpose),
            _ => None,
        }
    }
}
/// Request message for creating a survey from FHIR format
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateFhirSurveyRequest {
    /// FHIR questionnaire on a gRPC Struct format
    #[prost(message, optional, tag="1")]
    pub fhir_questionnaire: ::core::option::Option<::prost_types::Struct>,
}
/// Response message containing survey answers in FHIR format
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SurveyFhirAnswersResponse {
    /// The project identifier for this survey. Equal to the parent of the corresponding Agent.
    /// Format: <pre><code>projects/&lt;Project ID&gt;/agent</code></pre>
    #[prost(string, tag="1")]
    pub survey_id: ::prost::alloc::string::String,
    /// all requested answers
    #[prost(message, repeated, tag="2")]
    pub fhir_questionnaire_responses: ::prost::alloc::vec::Vec<::prost_types::Struct>,
}
include!("ondewo.survey.tonic.rs");
// @@protoc_insertion_point(module)
